services:
  - type: web
    name: chat-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: AI_SERVICE_URL
        sync: false
