services:
  - type: web
    name: chat-ai-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask run --host=0.0.0.0 --port=$PORT
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
